const scale = [
    { name: "", divisor: 1 },
    { name: "million", divisor: 1e6 },
    { name: "billion", divisor: 1e9 },
    { name: "trillion", divisor: 1e12 },
    { name: "quadrillion", divisor: 1e15 },
    { name: "quintillion", divisor: 1e18 },
    { name: "sextillion", divisor: 1e21 },
    { name: "septillion", divisor: 1e24 },
    { name: "octillion", divisor: 1e27 },
    { name: "nonillion", divisor: 1e30 },
    { name: "decillion", divisor: 1e33 },
    { name: "undecillion", divisor: 1e36 },
    { name: "duodecillion", divisor: 1e39 },
    { name: "tredecillion", divisor: 1e42 },
    { name: "quattuordecillion", divisor: 1e45 },
    { name: "quindecillion", divisor: 1e48 },
    { name: "sexdecillion", divisor: 1e51 },
    { name: "septendecillion", divisor: 1e54 },
    { name: "octodecillion", divisor: 1e57 },
    { name: "novemdecillion", divisor: 1e60 },
    { name: "vigintillion", divisor: 1e63 },
    { name: "unvigintillion", divisor: 1e66 },
    { name: "duovigintillion", divisor: 1e69 },
    { name: "tresvigintillion", divisor: 1e72 },
    { name: "quattuorvigintillion", divisor: 1e75 },
    { name: "quinvigintillion", divisor: 1e78 },
    { name: "sexvigintillion", divisor: 1e81 },
    { name: "septenvigintillion", divisor: 1e84 },
    { name: "octovigintillion", divisor: 1e87 },
    { name: "novemvigintillion", divisor: 1e90 },
    { name: "trigintillion", divisor: 1e93 },
    { name: "untrigintillion", divisor: 1e96 },
    { name: "duotrigintillion", divisor: 1e99 },
    { name: "googol", divisor: 1e100 }, // Special case
    { name: "tretrigintillion", divisor: 1e102 },
    { name: "quattuortrigintillion", divisor: 1e105 },
    { name: "quintrigintillion", divisor: 1e108 },
    { name: "sextrigintillion", divisor: 1e111 },
    { name: "septentrigintillion", divisor: 1e114 },
    { name: "octotrigintillion", divisor: 1e117 },
    { name: "novemtrigintillion", divisor: 1e120 },
    { name: "quadragintillion", divisor: 1e123 },
    { name: "unquadragintillion", divisor: 1e126 },
    { name: "duoquadragintillion", divisor: 1e129 },
    { name: "trequadragintillion", divisor: 1e132 },
    { name: "quattuorquadragintillion", divisor: 1e135 },
    { name: "quinquadragintillion", divisor: 1e138 },
    { name: "sexquadragintillion", divisor: 1e141 },
    { name: "septenquadragintillion", divisor: 1e144 },
    { name: "octoquadragintillion", divisor: 1e147 },
    { name: "novemquadragintillion", divisor: 1e150 },
    { name: "quinquagintillion", divisor: 1e153 },
    { name: "unquinquagintillion", divisor: 1e156 },
    { name: "duoquinquagintillion", divisor: 1e159 },
    { name: "trequinquagintillion", divisor: 1e162 },
    { name: "quattuorquinquagintillion", divisor: 1e165 },
    { name: "quinquinquagintillion", divisor: 1e168 },
    { name: "sexquinquagintillion", divisor: 1e171 },
    { name: "septenquinquagintillion", divisor: 1e174 },
    { name: "octoquinquagintillion", divisor: 1e177 },
    { name: "novemquinquagintillion", divisor: 1e180 },
    { name: "sexagintillion", divisor: 1e183 },
    { name: "unsexagintillion", divisor: 1e186 },
    { name: "duosexagintillion", divisor: 1e189 },
    { name: "tresexagintillion", divisor: 1e192 },
    { name: "quattuorsexagintillion", divisor: 1e195 },
    { name: "quinsexagintillion", divisor: 1e198 },
    { name: "sexsexagintillion", divisor: 1e201 },
    { name: "septensexagintillion", divisor: 1e204 },
    { name: "octosexagintillion", divisor: 1e207 },
    { name: "novemsexagintillion", divisor: 1e210 },
    { name: "septuagintillion", divisor: 1e213 },
    { name: "unseptuagintillion", divisor: 1e216 },
    { name: "duoseptuagintillion", divisor: 1e219 },
    { name: "treseptuagintillion", divisor: 1e222 },
    { name: "quattuorseptuagintillion", divisor: 1e225 },
    { name: "quinseptuagintillion", divisor: 1e228 },
    { name: "sexseptuagintillion", divisor: 1e231 },
    { name: "septseptuagintillion", divisor: 1e234 },
    { name: "octoseptuagintillion", divisor: 1e237 },
    { name: "novemseptuagintillion", divisor: 1e240 },
    { name: "octogintillion", divisor: 1e243 },
    { name: "unoctogintillion", divisor: 1e246 },
    { name: "duooctogintillion", divisor: 1e249 },
    { name: "treoctogintillion", divisor: 1e252 },
    { name: "quattuoroctogintillion", divisor: 1e255 },
    { name: "quinoctogintillion", divisor: 1e258 },
    { name: "sexoctogintillion", divisor: 1e261 },
    { name: "septoctogintillion", divisor: 1e264 },
    { name: "octooctogintillion", divisor: 1e267 },
    { name: "novemoctogintillion", divisor: 1e270 },
    { name: "nonagintillion", divisor: 1e273 },
    { name: "unnonagintillion", divisor: 1e276 },
    { name: "duononagintillion", divisor: 1e279 },
    { name: "trenonagintillion", divisor: 1e282 },
    { name: "quattuornonagintillion", divisor: 1e285 },
    { name: "quinnonagintillion", divisor: 1e288 },
    { name: "sexnonagintillion", divisor: 1e291 },
    { name: "septnonagintillion", divisor: 1e294 },
    { name: "octononagintillion", divisor: 1e297 },
    { name: "novemnonagintillion", divisor: 1e300 },
    { name: "centillion", divisor: 1e303 },
    { name: "uncentillion", divisor: 1e306 },
    { name: "Infinity", divisor: 1e309 } // at 10 uncentillion, we return infinity and consider the game to be completed! We should give the user an achievement, and allow them to start from scratch
]
export default (number: number): string => {
    if(number < 1000) return number.toFixed(2)
    if(number < 1000000) return Math.ceil(number).toString()

    let suffix = ""
    let formattedNumber = number

    for(let i = scale.length - 1; i >= 0; i--){
        if(number >= scale[i].divisor){
            suffix = scale[i].name.toUpperCase()
            formattedNumber = number / scale[i].divisor
            break
        }
    }

    if(suffix === 'INFINITY') return suffix

    return parseFloat(formattedNumber.toFixed(3)) + " " + suffix
}